/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth.register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth.login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth.refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth.logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["auth.me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/organizations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["organizations.list"];
    put?: never;
    post: operations["organizations.create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/organizations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["organizations.getById"];
    put: operations["organizations.update"];
    post?: never;
    delete: operations["organizations.remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["projects.list"];
    put?: never;
    post: operations["projects.create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["projects.getById"];
    put: operations["projects.update"];
    post?: never;
    delete: operations["projects.remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description The request did not match the expected schema */
    HttpApiDecodeError: {
      issues: components["schemas"]["Issue"][];
      message: string;
      /** @enum {string} */
      _tag: "HttpApiDecodeError";
    };
    /** @description Represents an error encountered while parsing a value to match the schema */
    Issue: {
      /**
       * @description The tag identifying the type of parse issue
       * @enum {string}
       */
      _tag:
        | "Pointer"
        | "Unexpected"
        | "Missing"
        | "Composite"
        | "Refinement"
        | "Transformation"
        | "Type"
        | "Forbidden";
      /** @description The path to the property where the issue occurred */
      path: components["schemas"]["PropertyKey"][];
      /** @description A descriptive message explaining the issue */
      message: string;
    };
    PropertyKey:
      | string
      | number
      | {
          /** @enum {string} */
          _tag: "symbol";
          key: string;
        };
    EmailAlreadyTaken: {
      email: string;
      /** @enum {string} */
      _tag: "EmailAlreadyTaken";
    };
    TokenSigningFailed: {
      /** @enum {string} */
      _tag: "TokenSigningFailed";
    };
    StorageError: {
      /** @enum {string} */
      _tag: "StorageError";
    };
    TooManyRequests: {
      retryAfter: number;
      /** @enum {string} */
      _tag: "TooManyRequests";
    };
    InvalidCredentials: {
      /** @enum {string} */
      _tag: "InvalidCredentials";
    };
    RefreshTokenExpired: {
      /** @enum {string} */
      _tag: "RefreshTokenExpired";
    };
    NotAuthenticated: {
      /** @enum {string} */
      _tag: "NotAuthenticated";
    };
    OrganizationNameTaken: {
      name: string;
      /** @enum {string} */
      _tag: "OrganizationNameTaken";
    };
    OrganizationNameReserved: {
      name: string;
      /** @enum {string} */
      _tag: "OrganizationNameReserved";
    };
    OrganizationNotFound: {
      id: string;
      /** @enum {string} */
      _tag: "OrganizationNotFound";
    };
    OrganizationInUse: {
      id: string;
      /** @enum {string} */
      _tag: "OrganizationInUse";
    };
    ProjectNotFound: {
      id: string;
      /** @enum {string} */
      _tag: "ProjectNotFound";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "auth.register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description a string that will be trimmed */
          email: string;
          /**
           * maxLength(256)
           * @description a string at most 256 character(s) long
           */
          password: string;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              /** @description a string that will be trimmed */
              email: string;
            };
          };
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description EmailAlreadyTaken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailAlreadyTaken"];
        };
      };
      /** @description TooManyRequests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TooManyRequests"];
        };
      };
      /** @description TokenSigningFailed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["TokenSigningFailed"]
            | components["schemas"]["StorageError"];
        };
      };
    };
  };
  "auth.login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description a string that will be trimmed */
          email: string;
          /**
           * maxLength(256)
           * @description a string at most 256 character(s) long
           */
          password: string;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              /** @description a string that will be trimmed */
              email: string;
            };
          };
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description InvalidCredentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvalidCredentials"];
        };
      };
      /** @description TooManyRequests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TooManyRequests"];
        };
      };
      /** @description TokenSigningFailed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["TokenSigningFailed"]
            | components["schemas"]["StorageError"];
        };
      };
    };
  };
  "auth.refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              /** @description a string that will be trimmed */
              email: string;
            };
          };
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description RefreshTokenExpired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RefreshTokenExpired"];
        };
      };
      /** @description TooManyRequests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TooManyRequests"];
        };
      };
      /** @description TokenSigningFailed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["TokenSigningFailed"]
            | components["schemas"]["StorageError"];
        };
      };
    };
  };
  "auth.logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageError"];
        };
      };
    };
  };
  "auth.me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              /** @description a string that will be trimmed */
              email: string;
            };
          };
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description NotAuthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotAuthenticated"];
        };
      };
    };
  };
  "organizations.list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            /** @description a string that will be trimmed */
            name: string;
            description?: string;
          }[];
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description NotAuthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotAuthenticated"];
        };
      };
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageError"];
        };
      };
    };
  };
  "organizations.create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description a string that will be trimmed */
          name: string;
          description?: string;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            /** @description a string that will be trimmed */
            name: string;
            description?: string;
          };
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description NotAuthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotAuthenticated"];
        };
      };
      /** @description OrganizationNameTaken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["OrganizationNameTaken"]
            | components["schemas"]["OrganizationNameReserved"];
        };
      };
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageError"];
        };
      };
    };
  };
  "organizations.getById": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            /** @description a string that will be trimmed */
            name: string;
            description?: string;
          };
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description NotAuthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotAuthenticated"];
        };
      };
      /** @description OrganizationNotFound */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationNotFound"];
        };
      };
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageError"];
        };
      };
    };
  };
  "organizations.update": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description a string that will be trimmed */
          name?: string;
          description?: string;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            /** @description a string that will be trimmed */
            name: string;
            description?: string;
          };
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description NotAuthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotAuthenticated"];
        };
      };
      /** @description OrganizationNotFound */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationNotFound"];
        };
      };
      /** @description OrganizationNameTaken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["OrganizationNameTaken"]
            | components["schemas"]["OrganizationNameReserved"];
        };
      };
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageError"];
        };
      };
    };
  };
  "organizations.remove": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description NotAuthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotAuthenticated"];
        };
      };
      /** @description OrganizationNotFound */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationNotFound"];
        };
      };
      /** @description OrganizationInUse */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationInUse"];
        };
      };
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageError"];
        };
      };
    };
  };
  "projects.list": {
    parameters: {
      query?: {
        ownerId?: string;
        organizationId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            /** @description a string that will be trimmed */
            name: string;
            description?: string;
            organizationId: string;
            ownerId: string;
            createdAt: string;
          }[];
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description NotAuthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotAuthenticated"];
        };
      };
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageError"];
        };
      };
    };
  };
  "projects.create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description a string that will be trimmed */
          name: string;
          description?: string;
          organizationId: string;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            /** @description a string that will be trimmed */
            name: string;
            description?: string;
            organizationId: string;
            ownerId: string;
            createdAt: string;
          };
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description NotAuthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotAuthenticated"];
        };
      };
      /** @description OrganizationNotFound */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationNotFound"];
        };
      };
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageError"];
        };
      };
    };
  };
  "projects.getById": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            /** @description a string that will be trimmed */
            name: string;
            description?: string;
            organizationId: string;
            ownerId: string;
            createdAt: string;
          };
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description NotAuthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotAuthenticated"];
        };
      };
      /** @description ProjectNotFound */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectNotFound"];
        };
      };
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageError"];
        };
      };
    };
  };
  "projects.update": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description a string that will be trimmed */
          name?: string;
          description?: string;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            /** @description a string that will be trimmed */
            name: string;
            description?: string;
            organizationId: string;
            ownerId: string;
            createdAt: string;
          };
        };
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description NotAuthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotAuthenticated"];
        };
      };
      /** @description ProjectNotFound */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectNotFound"];
        };
      };
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageError"];
        };
      };
    };
  };
  "projects.remove": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The request did not match the expected schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpApiDecodeError"];
        };
      };
      /** @description NotAuthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotAuthenticated"];
        };
      };
      /** @description ProjectNotFound */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectNotFound"];
        };
      };
      /** @description StorageError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StorageError"];
        };
      };
    };
  };
}
